provider:
  name: protocols

data_sources:
  aggregate_route:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes/{name}
      method: GET

  aggregate_route_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes
      method: GET

  app_group:
    read:
      path: /apps/protocols.eda.nokia.com
      method: GET

  bgp_group:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups/{name}
      method: GET

  bgp_group_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups
      method: GET

  bgp_peer:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers/{name}
      method: GET

  bgp_peer_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers
      method: GET

  check_default_bgp_peers:
    read:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss/{name}
      method: GET

  check_default_bgp_peers_list:
    read:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss
      method: GET

  default_aggregate_route:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes/{name}
      method: GET

  default_aggregate_route_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes
      method: GET

  default_bgp_group:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups/{name}
      method: GET

  default_bgp_group_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups
      method: GET

  default_bgp_peer:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers/{name}
      method: GET

  default_bgp_peer_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers
      method: GET

  default_ospf_area:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas/{name}
      method: GET

  default_ospf_area_deployment:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments/{name}
      method: GET

  default_ospf_area_deployment_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments
      method: GET

  default_ospf_area_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas
      method: GET

  default_ospf_instance:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances/{name}
      method: GET

  default_ospf_instance_deployment:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments/{name}
      method: GET

  default_ospf_instance_deployment_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments
      method: GET

  default_ospf_instance_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances
      method: GET

  default_ospf_interface:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces/{name}
      method: GET

  default_ospf_interface_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces
      method: GET

  default_route_reflector:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors/{name}
      method: GET

  default_route_reflector_client:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients/{name}
      method: GET

  default_route_reflector_client_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients
      method: GET

  default_route_reflector_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors
      method: GET

  default_static_route:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes/{name}
      method: GET

  default_static_route_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes
      method: GET

  ospf_area:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas/{name}
      method: GET

  ospf_area_deployment:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments/{name}
      method: GET

  ospf_area_deployment_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments
      method: GET

  ospf_area_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas
      method: GET

  ospf_instance:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances/{name}
      method: GET

  ospf_instance_deployment:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments/{name}
      method: GET

  ospf_instance_deployment_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments
      method: GET

  ospf_instance_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances
      method: GET

  ospf_interface:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces/{name}
      method: GET

  ospf_interface_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces
      method: GET

  resource_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1
      method: GET

  route_reflector:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors/{name}
      method: GET

  route_reflector_client:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients/{name}
      method: GET

  route_reflector_client_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients
      method: GET

  route_reflector_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors
      method: GET

  static_route:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes/{name}
      method: GET

  static_route_list:
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes
      method: GET

  workflow_get_inputs_resp_elem:
    read:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss/{name}/_input
      method: GET

resources:
  aggregate_route:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/aggregateroutes/{name}
      method: DELETE

  bgp_group:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgpgroups/{name}
      method: DELETE

  bgp_peer:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/bgppeers/{name}
      method: DELETE

  check_default_bgp_peers:
    create:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss
      method: POST
    read:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss/{name}
      method: GET
    delete:
      path: /workflows/v1/protocols.eda.nokia.com/v1/namespaces/{namespace}/checkdefaultbgppeerss/{name}
      method: DELETE

  default_aggregate_route:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultaggregateroutes/{name}
      method: DELETE

  default_bgp_group:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgpgroups/{name}
      method: DELETE

  default_bgp_peer:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultbgppeers/{name}
      method: DELETE

  default_ospf_area:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareas/{name}
      method: DELETE

  default_ospf_area_deployment:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfareadeployments/{name}
      method: DELETE

  default_ospf_instance:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstances/{name}
      method: DELETE

  default_ospf_instance_deployment:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinstancedeployments/{name}
      method: DELETE

  default_ospf_interface:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultospfinterfaces/{name}
      method: DELETE

  default_route_reflector:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectors/{name}
      method: DELETE

  default_route_reflector_client:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultroutereflectorclients/{name}
      method: DELETE

  default_static_route:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/defaultstaticroutes/{name}
      method: DELETE

  ospf_area:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareas/{name}
      method: DELETE

  ospf_area_deployment:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfareadeployments/{name}
      method: DELETE

  ospf_instance:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstances/{name}
      method: DELETE

  ospf_instance_deployment:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinstancedeployments/{name}
      method: DELETE

  ospf_interface:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/ospfinterfaces/{name}
      method: DELETE

  route_reflector:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectors/{name}
      method: DELETE

  route_reflector_client:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/routereflectorclients/{name}
      method: DELETE

  static_route:
    create:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes
      method: POST
    read:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes/{name}
      method: GET
    update:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes/{name}
      method: PUT
    delete:
      path: /apps/protocols.eda.nokia.com/v1/namespaces/{namespace}/staticroutes/{name}
      method: DELETE
